// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.qualimente.reliability;

import com.qualimente.reliability.Example;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Example_Roo_Configurable {
    
    declare @type: Example: @Configurable;
    
}
