// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.qualimente.reliability;

import com.qualimente.reliability.ExampleDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ExampleDataOnDemand_Roo_Configurable {
    
    declare @type: ExampleDataOnDemand: @Configurable;
    
}
